---
- name: "has stopped {{ ksm_service_name }} service"
  become: true
  service:
    name: "{{ ksm_service_name }}"
    enabled: no
    state: stopped
  ignore_errors: yes

- name: "has not /etc/systemd/system/{{ ksm_service_name }}.service on host"
  become: true
  file:
    path: "/etc/systemd/system/{{ ksm_service_name }}.service"
    state: absent
  notify: reload systemctl daemon

- name: "has not {{ ksm_host_source_file }} on host"
  become: true
  file:
    path: "{{ ksm_host_source_file }}"
    state: absent

- name: "has not {{ ksm_service_name }} config directory on host"
  file:
    path: "{{ ksm_host_config_dir }}"
    state: absent
